.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. baricoin_qt test_baricoin_qt
clean: FORCE
	$(MAKE) -C .. baricoin_qt_clean test_baricoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_baricoin_qt_check
baricoin-qt baricoin-qt.exe: FORCE
	 $(MAKE) -C .. baricoin_qt
apk: FORCE
	$(MAKE) -C .. baricoin_qt_apk
