#ifndef BARICOIN_CHAINPARAMSSEEDS_H
#define BARICOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the baricoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x7d,0xc6,0xe2,0x21,0x1f,0xc7,
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // BARICOIN_CHAINPARAMSSEEDS_H
